name: ci-golang-workflow
on:
  pull_request:
    branches: develop

jobs:
  check-application:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.22"] # Versões do Golang para execução
    steps:
      - uses: actions/checkout@v2 # Faz o checkout dos dados o último push para a máquina Ubuntu que irá rodar o script
      - uses: actions/setup-go@v2 # Instala o Golang na máquina
        with:
          go-version: ${{ matrix.go }} # Propriedades do matrix.go para versões do Golang
      - run: go test # Executa os testes
      - run: go run math.go # Executa o programa

      # Copiados da action "build-and-push-docker-images"
      # https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push # Faz o build da imagem e push para o Docker Hub
        uses: docker/build-push-action@v5
        with:
          push: true # Faz o push para o Docker Hub (false para apenas fazer o build)
          tags: vrbarreira/full-cycle-gh-actions:latest # Nome da imagem
